version: '2.2'
services:
  rqworker:
    build: .
    container_name: dojo-rq-worker
    networks:
      - dojo
    command:
      - rq
      - worker
      - --url
      - redis://${REDIS_HOST}:${REDIS_PORT}
      - high
      - default
      - low
  rqworker-rag:
    build:
      context: .
      dockerfile: Dockerfile.rag
    container_name: dojo-rq-worker-rag
    networks:
      - dojo
    command:
      - rq
      - worker
      - --url
      - redis://${REDIS_HOST}:${REDIS_PORT}
      - rag   
  rqworker-datamodeling:
    build:
      context: .
      dockerfile: Dockerfile.datamodeling
    container_name: dojo-rq-worker-datamodeling
    networks:
      - dojo
    command:
      - rq
      - worker
      - --url
      - redis://${REDIS_HOST}:${REDIS_PORT}
      - datamodeling
      
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
networks:
  dojo:
    driver: bridge
