version: '2.2'
services:
  rqworker:
    build: .
    container_name: dojo-rq-worker
    networks:
      - dojo
    command:
      - rq
      - worker
      - --url
      - redis://${REDIS_HOST}:${REDIS_PORT}
      - high
      - default
      - low
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
networks:
  dojo:
    driver: bridge
