version: '2'
services:
  postgres:
    image: postgres:14.4-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
  keycloak:
    image: docker-hub.uncharted.com/auth/keycloak:latest
    container_name: keycloak
    links:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: openidctest
    expose:
      - "8443"
      - "8080"
      - "9990"
    ports:
      - "8443:8443"