# generated by datamodel-codegen:
#   filename:  document-schema.json
#   timestamp: 2023-02-02T18:20:54+00:00

from __future__ import annotations


from typing import List, Optional, Any, Dict
# from xmlrpc.client import Boolean
from pydantic import BaseModel, Extra, Field

from doctest import Example

class Model(BaseModel):
    creation_date: Optional[str]
    mod_date: Optional[str]
    type: Optional[str]
    description: Optional[str]
    original_language: Optional[str]
    classification: Optional[str]
    title: Optional[str]
    publisher: Optional[str]
    producer: Optional[str]
    stated_genre: Optional[str]
