name: Build

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        node: [ '15' ]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ./ui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./ui/package-lock.json') }}

      - name: Npm Install
        working-directory: ./ui
        run: npm ci

      - name: Build Containers
        run: make docker_build
