name: Lint

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '15'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ./ui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./ui/package-lock.json') }}

      - name: Npm Install
        working-directory: ./ui
        run: npm install

      - name: Lint
        working-directory: ./ui
        run: npm run lint
