FROM node:lts
USER node

COPY --chown=node ui/package.json /ui/
COPY --chown=node ui/package-lock.json /ui/

WORKDIR /ui
RUN npm install

COPY --chown=node ui /ui

EXPOSE 8080
CMD ["npm", "run", "dev"]

