annotations = [   {   'coordinates_format': '',
        'data_type': 'int',
        'date_format': '',
        'description': 'A sample value that goes in meters',
        'display_name': 'No of Deaths',
        'field_name': 'fatalities',
        'geocode_level': '',
        'group': '',
        'primary': '',
        'qualifier_role': '',
        'qualifies': '',
        'unit': 'body_count',
        'unit_description': 'deaths'},
    {   'coordinates_format': '',
        'data_type': 'admin0',
        'date_format': '',
        'description': 'all_gadm_levels',
        'display_name': '',
        'field_name': 'country',
        'geocode_level': 'admin0',
        'group': 'main_geo',
        'primary': 'Y',
        'qualifier_role': '',
        'qualifies': '',
        'unit': '',
        'unit_description': ''},
    {   'coordinates_format': '',
        'data_type': 'admin1',
        'date_format': '',
        'description': 'all_gadm_levels',
        'display_name': '',
        'field_name': 'admin1',
        'geocode_level': 'admin1',
        'group': 'main_geo',
        'primary': 'Y',
        'qualifier_role': '',
        'qualifies': '',
        'unit': '',
        'unit_description': ''},
    {   'coordinates_format': '',
        'data_type': 'admin2',
        'date_format': '',
        'description': 'all_gadm_levels',
        'display_name': '',
        'field_name': 'admin2',
        'geocode_level': 'admin2',
        'group': 'main_geo',
        'primary': 'Y',
        'qualifier_role': '',
        'qualifies': '',
        'unit': '',
        'unit_description': ''},
    {   'coordinates_format': '',
        'data_type': 'admin3',
        'date_format': '',
        'description': 'all_gadm_levels',
        'display_name': '',
        'field_name': 'admin3',
        'geocode_level': 'admin3',
        'group': 'main_geo',
        'primary': 'Y',
        'qualifier_role': '',
        'qualifies': '',
        'unit': '',
        'unit_description': ''},
    {   'coordinates_format': '',
        'data_type': 'string',
        'date_format': '',
        'description': 'general region of main_geo',
        'display_name': 'General Region',
        'field_name': 'region',
        'geocode_level': '',
        'group': '',
        'primary': '',
        'qualifier_role': 'breakdown',
        'qualifies': 'main_geo',
        'unit': 'n/a',
        'unit_description': ''},
    {   'coordinates_format': '',
        'data_type': 'month',
        'date_format': '%m',
        'description': 'sample date',
        'display_name': '',
        'field_name': 'date_month',
        'geocode_level': '',
        'group': 'main_date',
        'primary': 'Y',
        'qualifier_role': '',
        'qualifies': '',
        'unit': '',
        'unit_description': ''},
    {   'coordinates_format': '',
        'data_type': 'day',
        'date_format': '%d',
        'description': 'sample date',
        'display_name': '',
        'field_name': 'date_day',
        'geocode_level': '',
        'group': 'main_date',
        'primary': 'Y',
        'qualifier_role': '',
        'qualifies': '',
        'unit': '',
        'unit_description': ''},
    {   'coordinates_format': '',
        'data_type': 'year',
        'date_format': '%Y',
        'description': 'sample date',
        'display_name': '',
        'field_name': 'date_year',
        'geocode_level': '',
        'group': 'main_date',
        'primary': 'Y',
        'qualifier_role': '',
        'qualifies': '',
        'unit': '',
        'unit_description': ''}]
