FROM node:17-buster
USER node

COPY --chown=node package.json /ui/
COPY --chown=node package-lock.json /ui/

WORKDIR /ui
RUN npm install

COPY --chown=node . /ui

ENV NODE_OPTIONS=--openssl-legacy-provider
EXPOSE 8080
CMD ["npm", "run", "dev"]

