aws s3 cp example.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp example.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp indicator_groups.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp indicator-self-registration.ipynb s3://jataware-world-modelers/transition/datasets//
aws s3 cp upload.sh s3://jataware-world-modelers/transition/datasets//
aws s3 cp upload_wbi_data.py s3://jataware-world-modelers/transition/datasets//
aws s3 cp data: s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDICountry.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDICountry-Series.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI_csv.zip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDIData.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDIFootNote.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDISeries.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDISeries-Time.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp output: s3://jataware-world-modelers/transition/datasets//
aws s3 cp awscli-bundle s3://jataware-world-modelers/transition/datasets//
aws s3 cp awscli-bundle.zip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp agricultural.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp agricultural_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp agricultural.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp balance_exports.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp balance_exports_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp balance_exports.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp balance_money.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp balance_money_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp balance_money.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp balances.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp balances_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp balances.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp capital_market.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp capital_market_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp capital_market.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp debt.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp debt_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp debt.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.adult.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.adult_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.adult.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.enrollment.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.enrollment_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.enrollment.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.expenditure.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.expenditure_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.expenditure.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.preprimary.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.preprimary_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.preprimary.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.primary.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.primary_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.primary.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.secondary.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.secondary_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.secondary.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.tertiary.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.tertiary_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp education.tertiary.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp energy.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp energy_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp energy.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp energy_price.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp energy_price_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp energy_price.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp environment.EN.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp environment.EN_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp environment.EN.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp environment.ER.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp environment.ER_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp environment.ER.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp external_debt.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp external_debt_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp external_debt.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp financial_banking.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp financial_banking_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp financial_banking.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp financial_monetary.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp financial_monetary_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp financial_monetary.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp financial_prices.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp financial_prices_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp financial_prices.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp findex.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp findex_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp findex.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp foreign.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp foreign_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp foreign.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp fund.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp fund_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp fund.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp funds.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp funds_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp funds.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp government_currency.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp government_currency_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp government_currency.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.alcohol.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.alcohol_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.alcohol.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.anemia.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.anemia_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.anemia.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.condom.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.condom_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.condom.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.death.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.death_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.death.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.dying.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.dying_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.dying.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.expenditure.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.expenditure_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.expenditure.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.HIV.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.HIV_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.HIV.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.immunization.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.immunization_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.immunization.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.malaria.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.malaria_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.malaria.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.maternal_mortality.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.maternal_mortality_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.maternal_mortality.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.medical.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.medical_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.medical.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.prevalence.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.prevalence_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.prevalence.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.severe.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.severe_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.severe.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.standard.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.standard_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.standard.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.surgery.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.surgery_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.surgery.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.tuberculosis.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.tuberculosis_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.tuberculosis.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.universal_health_coverage.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.universal_health_coverage_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.universal_health_coverage.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.water.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.water_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SH.water.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SP.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SP_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp health.SP.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp human_development.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp human_development_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp human_development.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp incidence.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp incidence_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp incidence.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp inclusionequity.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp inclusionequity_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp inclusionequity.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp information_technology.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp information_technology_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp information_technology.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp infrastructure.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp infrastructure_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp infrastructure.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp intellectual_property.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp intellectual_property_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp intellectual_property.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp interest_rate.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp interest_rate_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp interest_rate.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp investment.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp investment_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp investment.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp labor_market.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp labor_market_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp labor_market.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp logistics_performance.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp logistics_performance_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp logistics_performance.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp miscellaneous.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp miscellaneous_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp miscellaneous.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp missiles.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp missiles_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp missiles.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp national_accounts.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp national_accounts_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp national_accounts.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp national_expenditure.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp national_expenditure_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp national_expenditure.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp national_value.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp national_value_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp national_value.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp parity.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp parity_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp parity.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp share_income.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp share_income_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp share_income.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp socal_assistance.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp socal_assistance_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp socal_assistance.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.agriculture.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.agriculture_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.agriculture.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.employment.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.employment_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.employment.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.family.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.family_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.family.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_gender.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_gender_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_gender.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.industry.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.industry_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.industry.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_insurance.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_insurance_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_insurance.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.manufacturing.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.manufacturing_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.manufacturing.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_migration.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_migration_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_migration.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_protection.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_protection_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social_protection.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.selfemployed.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.selfemployed_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.selfemployed.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.services.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.services_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.services.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.total_labor_force.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.total_labor_force_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.total_labor_force.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.unemployment.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.unemployment_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.unemployment.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.wage.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.wage_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp social.wage.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp supplementation.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp supplementation_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp supplementation.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp trade_exports.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp trade_exports_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp trade_exports.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp trade_imports.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp trade_imports_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp trade_imports.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp travel_tourism.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp travel_tourism_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp travel_tourism.parquet.gzip s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp violence.csv s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp violence_meta.json s3://jataware-world-modelers/transition/datasets//
aws s3 cp WDI s3://jataware-world-modelers/transition/datasets//
aws s3 cp - s3://jataware-world-modelers/transition/datasets//
aws s3 cp violence.parquet.gzip s3://jataware-world-modelers/transition/datasets//
