name: Dojo API Unit Tests

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - api/**

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          cache: pip
          cache-dependency-path: api/requirements.txt
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies tests
        run: |
          pip install pytest
      - name: Run tests
        run: pytest

       run: pytest -vvs
